name: release

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  release:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/release.yml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
